# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7k70tfbg676-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/tim/school/spring2015/cs147/labs/lab_02/lab_02.cache/wt [current_project]
set_property parent.project_path /home/tim/school/spring2015/cs147/labs/lab_02/lab_02.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/tim/school/spring2015/cs147/labs/inv.v
  /home/tim/school/spring2015/cs147/labs/dff.v
  /home/tim/school/spring2015/cs147/labs/tff.v
  /home/tim/school/spring2015/cs147/labs/rcounter.v
  /home/tim/school/spring2015/cs147/labs/rcounter_tb.v
}
catch { write_hwdef -file RIPPLE_COUNTER_TB.hwdef }
synth_design -top RIPPLE_COUNTER_TB -part xc7k70tfbg676-1
write_checkpoint -noxdef RIPPLE_COUNTER_TB.dcp
catch { report_utilization -file RIPPLE_COUNTER_TB_utilization_synth.rpt -pb RIPPLE_COUNTER_TB_utilization_synth.pb }
